services:
  tavernemon:
    image: docker.io/itzg/minecraft-server
    container_name: tavernemon
    tty: true
    stdin_open: true
    networks:
      - minecraft
    ports:
      - 25565:25565/tcp
    environment:
      ALLOW_FLIGHT: "true"
      DIFFICULTY: "peaceful"
      EXISTING_OPS_FILE: "MERGE"
      EULA: "TRUE"
      GUI: "FALSE"
      LOG_IPS: "false"
      MAX_PLAYERS: "4"
      MAX_TICK_TIME: "-1"
      MEMORY: "6G"
      MOTD: "Bienvenue sur TaverneMon!"
      NETWORK_COMPRESSION_THRESHOLD: "-1"
      OPS: |-
        Tavsam
      PACKWIZ_URL: "https://samtvn.github.io/tavernemon/server/pack.toml"
      PLAYER_IDLE_TIMEOUT: "10"
      PREVENT_PROXY_CONNECTIONS: "true"
      REGION_FILE_COMPRESSION: "lz4"
      SERVER_NAME: "Tavernemon"
      SNOOPER_ENABLED: "false"
      SPAWN_MONSTERS: "false"
      SPAWN_PROTECTION: "0"
      STOP_SERVER_ANNOUNCE_DELAY: 2500
      STOP_DURATION: 3000
      TYPE: "FABRIC"
      TZ: "Europe/Berlin"
      USE_AIKAR_FLAGS: "true"
      VERSION: "1.21.1"
      VIEW_DISTANCE: "10"
    volumes:
      - ~/minecraft:/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  minecraft:
    name: minecraft_network
    external: true
