name = "TaverneMon"
author = "Viresme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2839fba688f9b4ac5fd00b7bea33a2cc58a92df1c481f67c53c18269e5826a41"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
