# Enable multiple megas at one time
# Allowed values: true, false - Default: false
multipleMegas = false

# Enable mega evolution only for battles
# Allowed values: true, false - Default: false
battleModeOnly = false

# Makes it so that evolving during battle consumes one turn (Only works if battleMode is enabled)
# Allowed values: true, false - Default: false
megaTurns = false

# Makes it so you can devolve and evolve the pokemon with mega bracelet in the same hand
# Allowed values: true, false - Default: false
braceletHandSensitive = false

# Allows you to have outside megas but they devolve on battle and then you can have battle mode style theme
# Allowed values: true, false - Default: false
battleMode = false

