name = "TaverneMon"
author = "Viresme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3d4365cd6d86ad7afc12b68d253f775b2ef18893fc7669c500f2f67e5cfa44c"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
