name = "TaverneMon"
author = "Viresme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05113ccf1b2fdc691c61b9a8dccd829e6ff6ecfcb4a9433d0da0a6945c74d7eb"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
