name = "TaverneMon"
author = "Viresme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f89b314ead1454c8e8cf9d961b013f78317d27f639c36b9120f16f74b4a0a26"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
