name = "TaverneMon"
author = "Viresme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32f28e93c07011c3ea14ff317e8c5b246b10fd210e0974eea5998ade55122776"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "datapacks"
